apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devsecops-app
  template:
    metadata:
      labels:
        app: devsecops-app
    spec:
      containers:
      - image: lohitakshay/devsecops-project:latest
        name: devsecops-app
        ports:
        - containerPort: 3000

