apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops-app
spec:
  replicas: 2  # Number of instances of the application to run
  selector:
    matchLabels:
      app: devsecops-app
  template:
    metadata:
      labels:
        app: devsecops-app
    spec:
      containers:
      - name: devsecops-app
        image: looooohit/devsecops-project:latest  # Docker image to use (match your pipeline image)
        ports:
        - containerPort: 3000  # Port on which the app listens inside the container
---
apiVersion: v1
kind: Service
metadata:
  name: devsecops-app-service
spec:
  selector:
    app: devsecops-app  # This should match the label in the deployment
  ports:
    - protocol: TCP
      port: 80       # Port exposed by the service
      targetPort: 3000  # Port on the container that the service maps to
  type: LoadBalancer  # Type of service to expose the application

